-- ============================================================
-- Waiting lists for sold-out pieces.
--
-- Safe to run on the live site: it only adds a table. Nothing reads it until
-- the new client ships, and nothing sends until the on_product_restocked
-- webhook is created.
-- ============================================================

create table if not exists public.restock_requests (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  email text,
  phone text,                      -- E.164, normalised the same way as checkout
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  notified_at timestamptz,         -- null while still waiting
  -- A request with neither is a row nobody can ever be told about.
  constraint restock_contact_required check (email is not null or phone is not null)
);

alter table public.restock_requests enable row level security;

-- Anyone may ask to be told, signed in or not: being made to create an account
-- to join a waiting list is how a waiting list stays empty.
create policy "restock_insert_anyone"
  on public.restock_requests for insert
  with check (true);

-- But the table is a list of customers' email addresses and phone numbers, so
-- nobody except an admin may read it back.
create policy "restock_select_admin"
  on public.restock_requests for select
  using (public.is_admin());

create policy "restock_update_admin"
  on public.restock_requests for update
  using (public.is_admin())
  with check (public.is_admin());

create policy "restock_delete_admin"
  on public.restock_requests for delete
  using (public.is_admin());

-- One live entry per person per piece. Scoped to un-notified rows so that
-- someone who was told last time can ask again the next time it sells out.
create unique index if not exists restock_pending_email
  on public.restock_requests (product_id, email)
  where notified_at is null and email is not null;

create unique index if not exists restock_pending_phone
  on public.restock_requests (product_id, phone)
  where notified_at is null and phone is not null;

-- Signed-out shoppers insert as anon; only signed-in admins ever read, and the
-- policy above is what actually restricts that.
grant insert on public.restock_requests to anon, authenticated;
grant select, update, delete on public.restock_requests to authenticated;
