-- ============================================================
-- Dina's Studio: profiles, products, orders + RLS
-- Run once in Supabase Dashboard > SQL Editor > New query > Run
--
-- On a fresh database, run these after it, in order:
--   product-images-bucket.sql   storage for product photos
--   profiles-email-integrity.sql
--   place-order.sql             REQUIRED — checkout calls place_order, and
--                               nothing below grants a direct insert into orders
-- ============================================================

-- ---------- profiles ----------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  -- Unique mirrors auth.users, which already enforces one account per address.
  -- Kept in step by the on_auth_user_email_changed trigger below, since the
  -- signup trigger alone would let this copy go stale after an email change.
  email text not null unique,
  name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','admin')),
  "createdAt" timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Read the caller's role with RLS bypassed. A policy on profiles that queries
-- profiles inline would re-trigger itself and abort with 42P17 (infinite
-- recursion), so every admin check goes through these helpers instead.
create or replace function public.current_profile_role()
returns text
language sql
security definer
set search_path = public
stable
as $$ select role from public.profiles where id = auth.uid() $$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$ select coalesce(public.current_profile_role() = 'admin', false) $$;

create policy "profiles_select_own_or_admin"
  on public.profiles for select
  using (auth.uid() = id or public.is_admin());

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id and role = public.current_profile_role());

-- Auto-create a profile row whenever someone signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Keep profiles.email in step when someone changes their address in auth.
create or replace function public.sync_profile_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is distinct from old.email then
    update public.profiles set email = new.email where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row execute procedure public.sync_profile_email();

-- ---------- products ----------
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null,
  price numeric not null,
  pop int not null default 0,
  stock text not null default 'in' check (stock in ('in','low','out')),
  sizes jsonb not null default '[]',
  "soldOut" jsonb not null default '[]',
  "desc" text,
  fabric text,
  nw boolean not null default false,
  "paletteIndex" int not null default 0,
  images jsonb not null default '[]'
);

alter table public.products enable row level security;

create policy "products_select_all"
  on public.products for select
  using (true);

create policy "products_write_admin_only"
  on public.products for all
  using (public.is_admin())
  with check (public.is_admin());

-- ---------- orders ----------
create table public.orders (
  id text primary key,
  "userId" uuid not null references auth.users(id),
  date timestamptz not null default now(),
  "displayDate" text not null,
  status text not null default 'pending',
  customer jsonb not null,
  "shippingAddress" jsonb not null,
  "paymentMethod" text not null,
  items jsonb not null,
  subtotal numeric not null,
  shipping numeric not null,
  total numeric not null
);

alter table public.orders enable row level security;

-- No insert policy and no insert grant: orders are created only by
-- public.place_order (see place-order.sql), which claims the pieces and prices
-- the order in one transaction. A direct insert could do neither.

create policy "orders_select_own_or_admin"
  on public.orders for select
  using (auth.uid() = "userId" or public.is_admin());

create policy "orders_update_admin_only"
  on public.orders for update
  using (public.is_admin());

-- ---------- table privileges ----------
-- PostgREST connects as `anon` when signed out and `authenticated` when signed
-- in. RLS still decides which rows each may see; these only open the door.
grant usage on schema public to anon, authenticated;

grant select on public.products to anon, authenticated;
grant insert, update on public.products to authenticated;

grant select, update on public.profiles to authenticated;

grant select, update on public.orders to authenticated;
