-- ============================================================
-- Dina's Studio: profiles, products, orders + RLS
-- Run once in Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

-- ---------- profiles ----------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','admin')),
  "createdAt" timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles_select_own_or_admin"
  on public.profiles for select
  using (
    auth.uid() = id
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    and role = (select role from public.profiles where id = auth.uid())
  );

-- Auto-create a profile row whenever someone signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------- products ----------
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null,
  price numeric not null,
  pop int not null default 0,
  stock text not null default 'in' check (stock in ('in','low','out')),
  sizes jsonb not null default '[]',
  "soldOut" jsonb not null default '[]',
  "desc" text,
  fabric text,
  nw boolean not null default false,
  "paletteIndex" int not null default 0,
  images jsonb not null default '[]'
);

alter table public.products enable row level security;

create policy "products_select_all"
  on public.products for select
  using (true);

create policy "products_write_admin_only"
  on public.products for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- ---------- orders ----------
create table public.orders (
  id text primary key,
  "userId" uuid not null references auth.users(id),
  date timestamptz not null default now(),
  "displayDate" text not null,
  status text not null default 'pending',
  customer jsonb not null,
  "shippingAddress" jsonb not null,
  "paymentMethod" text not null,
  items jsonb not null,
  subtotal numeric not null,
  shipping numeric not null,
  total numeric not null
);

alter table public.orders enable row level security;

create policy "orders_insert_own"
  on public.orders for insert
  with check (auth.uid() = "userId");

create policy "orders_select_own_or_admin"
  on public.orders for select
  using (
    auth.uid() = "userId"
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

create policy "orders_update_admin_only"
  on public.orders for update
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
