-- ============================================================
-- Seeds the `products` table with the original 17 pieces.
-- Run once, after schema.sql, in the Supabase SQL Editor.
-- ============================================================

insert into public.products (id, name, cat, price, pop, stock, sizes, "soldOut", "desc", nw, images, fabric) values
(1, 'Black Cotton Set', 'Matching Sets', 588, 96, 'in', '["M-L"]', '[]', 'A relaxed two-piece in crinkled black cotton — oversized button-down shirt and matching wide-leg trouser with a soft, textured drape.', false, '["data/images/black_cotton_set_ML_160.jpg","data/images/black_cotton_set_ML_160(2).jpg"]', 'Crinkled Cotton'),
(2, 'Dark Green Cotton & Chiffon Set', 'Matching Sets', 588, 90, 'in', '["M-L"]', '[]', 'An olive-toned set in lightweight cotton layered with sheer chiffon, cut with patch pockets and a relaxed collar.', true, '["data/images/dark_green_cotton_with_chiffon_set_ML_160.jpg","data/images/dark_green_cotton_with_chiffon_set_ML_160(2).jpg"]', 'Cotton & Sheer Chiffon Blend'),
(3, 'Liberty Cotton Short Set', 'Matching Sets', 404, 88, 'in', '["One Size"]', '[]', 'A breezy short set in a mixed floral Liberty-style print, with a collared top, patch pocket, and matching tailored shorts.', false, '["data/images/liberty_cotton_short_set_110.jpg","data/images/liberty_cotton_short_set_110(2).jpg"]', 'Liberty-Print Cotton'),
(4, 'Liberty Cotton Short Set — Blue', 'Matching Sets', 404, 84, 'in', '["One Size"]', '[]', 'A ditsy blue floral short set with a belted, collared top and matching tailored shorts — finished in soft cream trim.', false, '["data/images/liberty_cotton_short_set_blue_110.jpg"]', 'Liberty-Print Cotton'),
(5, 'Liberty Cotton Short Set — Green', 'Matching Sets', 404, 82, 'in', '["One Size"]', '[]', 'A soft teal-and-cream print short set with a belted, collared top and matching tailored shorts.', false, '["data/images/liberty_cotton_short_set_green_110.jpg"]', 'Liberty-Print Cotton'),
(6, 'Silk Jacquard Set — Offwhite', 'Matching Sets', 551, 91, 'in', '["One Size"]', '[]', 'An ivory floral jacquard shirt and trouser set with a soft, fluid drape — finished with a relaxed collar and patch pocket.', false, '["data/images/silk_jaccard_set_offwhite.jpg","data/images/silk_jaccard_set_offwhite(2).jpg"]', 'Silk Jacquard'),
(7, 'Silk Jacquard Set — Light Blue', 'Matching Sets', 661, 85, 'in', '["One Size"]', '[]', 'A dusty blue medallion-print top and trouser set with cream contrast trim and a relaxed camp collar.', false, '["data/images/silk_jaccard_set_light_blue_180.jpg"]', 'Silk Jacquard'),
(8, 'Silk Jacquard Set — Emerald Dot', 'Matching Sets', 441, 80, 'in', '["One Size"]', '[]', 'A green ellipse-print top and wide-leg trouser set with a contrast ivory trim and patch pocket.', false, '["data/images/silk_jaccard_green_set_120.jpg"]', 'Silk Jacquard'),
(9, 'Silk Jacquard Set — Olive Medallion', 'Matching Sets', 441, 78, 'in', '["One Size"]', '[]', 'An olive medallion-print top and trouser set with piped ivory trim and a relaxed camp collar.', false, '["data/images/silk_jaccard_set_green_120.jpg"]', 'Silk Jacquard'),
(10, 'Polka Dot Linen Set', 'Matching Sets', 459, 87, 'in', '["S-M"]', '[]', 'A gathered polka-dot linen shirt set, shown in soft grey and warm sand — relaxed collar, patch pocket, elastic-waist trouser.', true, '["data/images/polka_dots_linen_sets_SM_125.jpg"]', 'Textured Linen'),
(11, 'Silk Satin Print Set', 'Matching Sets', 459, 83, 'in', '["S-M"]', '[]', 'A vibrant printed silk-satin set in a warm pink multicolor pattern, with a relaxed camp collar and matching wide-leg trouser.', false, '["data/images/silk_satin_pink_SM_125.jpg"]', 'Silk Satin'),
(12, 'Summer Kimono — Powder Blue', 'Kimonos', 220, 92, 'in', '["One Size"]', '[]', 'A flowing powder-blue kimono finished with a hand-embroidered gold and turquoise floral trim.', false, '["data/images/summer_kimono_blue_60.jpg","data/images/kimono_blue_and_purple.jpg"]', 'Soft Chiffon'),
(13, 'Summer Kimono — Lilac', 'Kimonos', 220, 89, 'in', '["One Size"]', '[]', 'A lilac kimono in a metallic gold floral print, edged with a shimmering gold and lavender trim.', false, '["data/images/summer_kimono_purple_60.jpg","data/images/kimono_blue_and_purple.jpg"]', 'Soft Cotton'),
(14, 'Summer Kimono — Green Silk', 'Kimonos', 257, 86, 'in', '["One Size"]', '[]', 'An emerald silk-brocade kimono with a delicate cream crochet-lace trim along the edges and sleeves.', true, '["data/images/summer_kimono_green_silk_70.jpg","data/images/summer_kimono_green_silk_70(2).jpg"]', 'Silk Brocade'),
(15, 'Summer Kimono — Polka Gold', 'Kimonos', 220, 81, 'in', '["One Size"]', '[]', 'A gold polka-dot kimono, shown here in blush pink and powder blue — a light layering piece for any set.', false, '["data/images/summer_kimono_polka_60.jpg","data/images/summer_kimono_polka_60(2).jpg"]', 'Cotton Voile'),
(16, 'Summer Kimono — Embroidered Coin', 'Kimonos', 202, 77, 'in', '["One Size"]', '[]', 'An ivory coin-print kimono finished with a hand-embroidered gold and green trim along the collar.', false, '["data/images/summer_kimono_with_embroidery_55.jpg"]', 'Satin with Embroidered Trim'),
(17, 'Summer Kimono — Sunset Paisley', 'Kimonos', 202, 75, 'in', '["One Size"]', '[]', 'A bold yellow paisley kimono with a rich red and blue print and floral embroidered trim.', false, '["data/images/summer_kimono_yellow_55.jpg"]', 'Cotton Sateen');

-- Keep the id sequence ahead of the explicit ids inserted above,
-- so the next admin-added product gets id 18, not a collision.
select setval(pg_get_serial_sequence('public.products', 'id'), 17, true);
